id: P22FBD7FE
initial_creation_type: ocr
source_metadata:
  volumes:
    b7e9e5d6d2154bd9bb648b896f4ffedf:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
